-- 合并特征生成ANALY_AIRLINE_MODEL_HOUR
INSERT INTO %1$s (SKEY, FLIGHT_DATE, INSERT_DATE, COMP, EQT, FLTNO, DEPTIME, ARRTIME, DEP, ARR, CAP, MAX, EX_DIF, IST_HOUR, OD, BKD, LKZK, REST, KZL, DEPWEEK, TIME_PD, TRANSIT, HAO, "HOUR", DEP_MINUTE, ARR_TIME, ARR_MINUTE, FLYHOURS, HX, "YEAR", "MONTH", WEEK, STD_PRICE, SUM_INCOME, SUM_INCOME_NEW, HDLX, DISTANCE, ZGLSR, HOLIDAY, MEMO, AIR, EQT_CODE, FLIGHTNO, UP_CITY_CODE, DIS_CITY_CODE, HX_CODE, OD_CODE, FLY_TIME, Y_CABIN_P, NUMOFSOLD, CABINS, PRICEARR, DIFF_IST_HOUR, DETAIL_DIFF_BKD, BKD_SUM, HIS_1, HIS_2, HIS_3, YOY_DATE, DEP_LONGITUDE, DEP_LATITUDE, ARR_LONGITUDE, ARR_LATITUDE, FLY_SEASON, CANCEL_BKG, AFFIRM_BKG, CAPACITY_P, CAPACITY, OD_MARKET_PER, CAP_P, CAP_SUM, COM_MARKET_PER, CAP_C, CAP_COUNT, AREA_MARKET_PER, KZL_P, REST_P, KZL_HIS_1, KZL_HIS_2, KZL_HIS_3, KZL_HIS_4, KZL_HIS_5, KZL_HIS_6, KZL_HIS_7, DETAIL_DIFF_BKD_1, DETAIL_PRICE, DETAIL_BKD, FINAL_DEMAND, DEMAND, D0_PRICEARR, D0_KZL, HIS_4, HIS_5, HIS_6, HIS_7, YOY_BKD, YOY_REST, YOY_BKD_SUM, YOY_DETAIL_DIFF_BKD, YOY_NUMOFSOLD, YOY_PRICEARR, WOW_FLIGHT_NO, YOY_FINAL_DEMAND, YOY_DEMAND, YOY_KZL, YOY_D0_KZL, YOY_BKD_1, YOY_REST_1, YOY_DIFF_BKD_1, YOY_D0_KZL_1, YOY_KZL_1, YOY_BKD_2, YOY_REST_2, YOY_DIFF_BKD_2, YOY_D0_KZL_2, YOY_KZL_2, YOY_BKD_3, YOY_REST_3, YOY_DIFF_BKD_3, YOY_D0_KZL_3, YOY_KZL_3, CLSN, CLSN_MAX, CLSN_CAP, CLSN_BKD, ID)
SELECT t.*, %16$s.Nextval
FROM (
    WITH t_0 AS (
        SELECT t.*, c.CODE AS air, ci.CODE AS up_city_code, ct.CODE AS dis_city_code, e.code as eqt_code,
            f.CODE AS flightno, o.CODE as od_code, h.CODE AS hx_code,
            (case when t.COMP = 'FM' then 'MU' ELSE t.COMP END) AIRCODE
        FROM %2$s t
        LEFT JOIN %3$s c
        ON t.COMP = c.COMP
        LEFT JOIN %4$s ci
        ON t.dep = ci.CITY
        LEFT JOIN %4$s ct
        ON t.arr = ct.CITY
        LEFT JOIN %5$s e
        ON t.eqt = e.EQT
        LEFT JOIN %6$s f
        ON t.fltno = f.FLT_NO
        LEFT JOIN %7$s o
        ON t.OD = o.OD
        LEFT JOIN %8$s h
        ON t.HX = h.HX
    ),
    t_1 AS (
        SELECT SKEY, t.FLIGHT_DATE, t.INSERT_DATE, t.COMP, EQT, t.FLTNO, DEPTIME, ARRTIME, t.DEP, t.ARR, CAP, MAX, t.EX_DIF, t.IST_HOUR, OD,
            BKD, (CASE WHEN y_cabin_p = 0 or affirm_bkg = 0 THEN 0 ELSE sum_income_new / y_cabin_p / affirm_bkg END) lkzk,
            REST, KZL, WEEK AS DEPWEEK, TIME_PD, TRANSIT, HAO, "HOUR", DEP_MINUTE, ARR_TIME, ARR_MINUTE,
            FLYHOURS, HX, "YEAR", "MONTH", WEEK, (CASE WHEN STD_PRICE = 0 THEN y_cabin_p ELSE STD_PRICE END) as STD_PRICE,
            SUM_INCOME, SUM_INCOME_NEW, HDLX, DISTANCE, A_BKG, B_BKG, C_BKG, D_BKG, E_BKG, F_BKG, G_BKG, H_BKG, I_BKG,
            J_BKG, K_BKG, L_BKG, M_BKG, N_BKG, O_BKG, P_BKG, Q_BKG, R_BKG, S_BKG, T_BKG, U_BKG, V_BKG, W_BKG, X_BKG, Y_BKG, Z_BKG,
            (CASE WHEN MAX = 0 or DISTANCE < 30 THEN 0 ELSE sum_income_new/max/DISTANCE END) zglsr,
            AIR, EQT_CODE, FLIGHTNO, UP_CITY_CODE, DIS_CITY_CODE, HX_CODE, OD_CODE, FLY_TIME, Y_CABIN_P, NUMOFSOLD, CABINS, PRICEARR,
            DIFF_IST_HOUR, DETAIL_DIFF_BKD, BKD_SUM, HIS_1, HIS_2, HIS_3, HIS_4, HIS_5, HIS_6, HIS_7, FLY_SEASON, CANCEL_BKG,
            AFFIRM_BKG, CAPACITY_P, CAPACITY, OD_MARKET_PER, CAP_P, CAP_SUM, COM_MARKET_PER, CAP_C, CAP_COUNT, AREA_MARKET_PER,
            KZL_P, REST_P, KZL_HIS_1, KZL_HIS_2, KZL_HIS_3, KZL_HIS_4, KZL_HIS_5, KZL_HIS_6, KZL_HIS_7, DETAIL_DIFF_BKG_1 AS DETAIL_DIFF_BKD_1,
            DETAIL_PRICE, DETAIL_BKD, CLSN, CLSN_MAX, CLSN_CAP, CLSN_BKD
        FROM t_0 t
        LEFT JOIN %10$s t1
        ON t.FLIGHT_DATE = t1.FLIGHT_DATE AND t.FLTNO = t1.FLTNO AND t.DEP = t1.DEP AND t.ARR = t1.ARR AND t.EX_DIF = t1.EX_DIF
        LEFT JOIN %11$s t2
        ON t.FLIGHT_DATE = t2.FLIGHT_DATE AND t.DEP = t2.DEP AND t.ARR = t2.ARR AND t.EX_DIF = t2.EX_DIF AND t.AIRCODE = t2.COMP
        LEFT JOIN %12$s t3
        ON t.FLIGHT_DATE = t3.FLIGHT_DATE AND t.FLTNO = t3.FLTNO AND t.DEP = t3.DEP AND t.ARR = t3.ARR AND t.INSERT_DATE = t3.INSERT_DATE
    ),
    %13$s
    t_7 AS (
        SELECT t.*, t1.numOfSold as final_demand, t1.kzl as d0_kzl, %14$s,
            %15$s
        FROM t_1 t
        LEFT JOIN t_6 t1
        ON t.FLIGHT_DATE = t1.FLIGHT_DATE AND t.FLTNO = t1.FLTNO AND t.DEP = t1.DEP AND t.ARR = t1.ARR
    )
    SELECT SKEY, t.FLIGHT_DATE, t.INSERT_DATE, COMP, EQT, t.FLTNO, DEPTIME, ARRTIME, t.DEP, t.ARR, CAP, MAX, EX_DIF, IST_HOUR, OD,
        BKD, lkzk, REST, KZL, DEPWEEK, TIME_PD, TRANSIT, HAO, "HOUR", DEP_MINUTE, ARR_TIME, ARR_MINUTE, FLYHOURS, HX,
        "YEAR", "MONTH", WEEK, STD_PRICE, SUM_INCOME, SUM_INCOME_NEW, HDLX, DISTANCE, zglsr, HOLIDAY, MEMO, AIR, EQT_CODE,
        FLIGHTNO, UP_CITY_CODE, DIS_CITY_CODE, HX_CODE, OD_CODE, FLY_TIME, Y_CABIN_P, NUMOFSOLD, CABINS, PRICEARR,
        DIFF_IST_HOUR, DETAIL_DIFF_BKD, BKD_SUM, HIS_1, HIS_2, HIS_3, YOY_DATE, -1 as DEP_LONGITUDE, -1 as DEP_LATITUDE,
        -1 as ARR_LONGITUDE, -1 as ARR_LATITUDE, FLY_SEASON, CANCEL_BKG, AFFIRM_BKG, CAPACITY_P, CAPACITY, OD_MARKET_PER, CAP_P, CAP_SUM,
        COM_MARKET_PER, CAP_C, CAP_COUNT, AREA_MARKET_PER, KZL_P, REST_P, KZL_HIS_1, KZL_HIS_2, KZL_HIS_3, KZL_HIS_4, KZL_HIS_5,
        KZL_HIS_6, KZL_HIS_7, DETAIL_DIFF_BKD_1, DETAIL_PRICE, DETAIL_BKD, final_demand, demand, D0_PRICEARR, d0_kzl, HIS_4, HIS_5,
        HIS_6, HIS_7, YOY_BKD, YOY_REST, YOY_BKD_SUM, YOY_DETAIL_DIFF_BKD, YOY_NUMOFSOLD, YOY_PRICEARR, WOW_FLIGHT_NO,
        YOY_FINAL_DEMAND, YOY_DEMAND, YOY_KZL, YOY_D0_KZL, YOY_BKD_1, YOY_REST_1, YOY_DIFF_BKD_1, YOY_D0_KZL_1,
        YOY_KZL_1, YOY_BKD_2, YOY_REST_2, YOY_DIFF_BKD_2, YOY_D0_KZL_2, YOY_KZL_2, YOY_BKD_3, YOY_REST_3, YOY_DIFF_BKD_3,
        YOY_D0_KZL_3, YOY_KZL_3, CLSN, CLSN_MAX, CLSN_CAP, CLSN_BKD
    FROM t_7 t
    LEFT JOIN %9$s t1
    ON t.FLIGHT_DATE = t1.FLIGHT_DATE AND t.FLTNO = t1.FLTNO AND t.DEP = t1.DEP AND t.ARR = t1.ARR AND t.INSERT_DATE = t1.INSERT_DATE
) t