-- 合并各特征表，生成ANALY_OTA_FEATURE
INSERT INTO %1$s (AIR_CODE, DEP, ARR, FLIGHT_DATE, FLIGHT_NO, CREATE_TIME, EX_DIF, DEP_CITY, ARR_CITY, DEP_TIME, ARR_TIME, LABEL, STD_PRICE, FLIGHT_TYPE_CODE, FPRICE, CPRICE, FEA_DELT_DEPTIME, AIRCODE_CLASS, FEA_NEAREST_TIME_1, FEA_NEAREST_TIME_2, TOP_1, TOP_2, TOP_3, TOP_4, TOP_5, TOP_6, TOP_MEAN, TOP_MAX, TOP_MIN, TOP_STD, FLIGHTS_TOTAL, FLIGHTS_SELF, POWER, FEA_HR, FEA_MONTH, FEA_DAY, FEA_WEEK, FEA_AIR_CODE, FEA_FLIGHT_NO, DISTANCE, FD_PRICE, SINGLE_LEG_TIME, AC_SINGLE_LEG_TIME, FEA_DEP, FEA_ARR, FEA_HR_CLASS, FLY_COUNT, FLY_NUM, FLY_RATE, LAST_1_FLY_NUM, LAST_1_FLY_COUNT, LAST_1_FLY_RATE, LAST_2_FLY_NUM, LAST_2_FLY_COUNT, LAST_2_FLY_RATE, LAST_3_FLY_NUM, LAST_3_FLY_COUNT, LAST_3_FLY_RATE, AFTER_1_FLY_NUM, AFTER_1_FLY_COUNT, AFTER_1_FLY_RATE, AFTER_2_FLY_NUM, AFTER_2_FLY_COUNT, AFTER_2_FLY_RATE, AFTER_3_FLY_NUM, AFTER_3_FLY_COUNT, AFTER_3_FLY_RATE, LOWEST_FLIGHT_NO, LOWEST_DEP_TIME, LOWEST_PRICE, ID)
SELECT t.*, %7$s.Nextval
FROM (
    SELECT t.AIR_CODE, t.DEP, t.ARR, t.FLIGHT_DATE, t.FLIGHT_NO, t.CREATE_TIME, t.EX_DIF, DEP_CITY, ARR_CITY, t.DEP_TIME, ARR_TIME,
        label, STD_PRICE, flight_type_code, FPRICE, CPRICE, FEA_DELT_DEPTIME, AIRCODE_CLASS, FEA_NEAREST_TIME_1,
        FEA_NEAREST_TIME_2, TOP_1, TOP_2, TOP_3, TOP_4, TOP_5, TOP_6, TOP_MEAN, TOP_MAX, TOP_MIN, TOP_STD,
        t3.FLYNUM as FLIGHTS_TOTAL, FLIGHTS_SELF,
        (CASE WHEN t3.FLYNUM is NULL THEN 0 ELSE FLIGHTS_SELF / t3.FLYNUM END) POWER,
        FEA_HR, FEA_MONTH, FEA_DAY, FEA_WEEK, FEA_AIR_CODE, FEA_FLIGHT_NO, DISTANCE, STD_PRICE AS FD_PRICE,
        SINGLE_LEG_TIME, AC_SINGLE_LEG_TIME, FEA_DEP, FEA_ARR, FEA_HR_CLASS, t3.FLYCOUNT as FLY_COUNT,
        t3.FLYNUM as FLY_NUM, t3.FLYRATE as FLY_RATE,
        last_1_fly_num, last_1_fly_count, last_1_fly_rate, last_2_fly_num, last_2_fly_count, last_2_fly_rate,
        last_3_fly_num, last_3_fly_count, last_3_fly_rate, after_1_fly_num, after_1_fly_count, after_1_fly_rate,
        after_2_fly_num, after_2_fly_count, after_2_fly_rate, after_3_fly_num, after_3_fly_count, after_3_fly_rate,
        LOWEST_FLIGHT_NO, LOWEST_DEP_TIME, LOWEST_PRICE
    FROM (
        SELECT * FROM %2$s WHERE AIR_CODE in (%6$s)
    ) t
    LEFT JOIN %3$s t2
    ON t.FLIGHT_DATE = t2.FLIGHT_DATE AND t.DEP = t2.DEP AND t.ARR = t2.ARR AND t.CREATE_TIME = t2.CREATE_TIME AND t.FLIGHT_NO = t2.FLIGHT_NO
    LEFT JOIN %4$s t3
    ON t.FLIGHT_DATE = t3.FLIGHT_DATE AND t.DEP = t3.DEP AND t.ARR = t3.ARR AND t.CREATE_TIME = t3.CREATE_TIME
    LEFT JOIN %5$s t4
    ON t.FLIGHT_DATE = t4.FLIGHT_DATE AND t.DEP = t4.DEP AND t.ARR = t4.ARR AND t.CREATE_TIME = t4.CREATE_TIME AND t.FLIGHT_NO = t4.FLIGHT_NO
) t