-- 寻找最接近的ANALY_AIRLINE_MODEL_HOUR的数据的时间，先寻找未来的，如果没有再寻找历史的
INSERT INTO %1$s (FLIGHT_DATE, AIR_CODE, FLIGHT_NO, DEP_TIME, DEP, ARR, CREATE_TIME, LABEL, TOP_1, TOP_2, TOP_3, TOP_4, TOP_5, TOP_6, FEA_AIR_CODE, FEA_FLIGHT_NO, FEA_DEP, FEA_ARR, EX_DIF, FEA_HR, FEA_HR_CLASS, AIRCODE_CLASS, FEA_NEAREST_TIME_1, FEA_NEAREST_TIME_2, FEA_DELT_DEPTIME, TOP_MEAN, TOP_MAX, TOP_MIN, TOP_STD, STD_PRICE, FLIGHTS_SELF, FLIGHTS_TOTAL, POWER, FEA_MONTH, FEA_DAY, FEA_WEEK, FLIGHT_TYPE_CODE, SINGLE_LEG_TIME, AC_SINGLE_LEG_TIME, LAST_3_FLY_NUM, LAST_3_FLY_COUNT, LAST_3_FLY_RATE, LAST_2_FLY_NUM, LAST_2_FLY_COUNT, LAST_2_FLY_RATE, LAST_1_FLY_NUM, LAST_1_FLY_COUNT, LAST_1_FLY_RATE, FLY_NUM, FLY_COUNT, FLY_RATE, AFTER_1_FLY_NUM, AFTER_1_FLY_COUNT, AFTER_1_FLY_RATE, AFTER_2_FLY_NUM, AFTER_2_FLY_COUNT, AFTER_2_FLY_RATE, AFTER_3_FLY_NUM, AFTER_3_FLY_COUNT, AFTER_3_FLY_RATE, LOWEST_FLIGHT_NO, LOWEST_DEP_TIME, LOWEST_PRICE, DISTANCE, FD_PRICE, DEP_CITY, ARR_CITY, SKEY, H_FLIGHT_DATE, INSERT_DATE, COMP, EQT, FLTNO, DEPTIME, ARRTIME, H_DEP, H_ARR, CAP, MAX, H_EX_DIF, IST_HOUR, OD, BKD, LKZK, REST, KZL, DEPWEEK, TIME_PD, TRANSIT, HAO, "HOUR", DEP_MINUTE, ARR_TIME, ARR_MINUTE, FLYHOURS, HX, "YEAR", "MONTH", WEEK, SUM_INCOME, SUM_INCOME_NEW, HDLX, ZGLSR, HOLIDAY, AIR, EQT_CODE, FLIGHTNO, UP_CITY_CODE, DIS_CITY_CODE, HX_CODE, OD_CODE, FLY_TIME, Y_CABIN_P, NUMOFSOLD, PRICEARR, FINAL_DEMAND, D0_KZL, DEMAND, D0_PRICEARR, DIFF_IST_HOUR, DETAIL_DIFF_BKD, BKD_SUM, HIS_1, HIS_2, HIS_3, HIS_4, HIS_5, HIS_6, HIS_7, YOY_DATE, YOY_BKD, YOY_REST, YOY_BKD_SUM, YOY_DETAIL_DIFF_BKD, YOY_NUMOFSOLD, YOY_PRICEARR, YOY_FINAL_DEMAND, YOY_DEMAND, YOY_KZL, YOY_D0_KZL, YOY_BKD_1, YOY_REST_1, YOY_DIFF_BKD_1, YOY_D0_KZL_1, YOY_KZL_1, YOY_BKD_2, YOY_REST_2, YOY_DIFF_BKD_2, YOY_D0_KZL_2, YOY_KZL_2, YOY_BKD_3, YOY_REST_3, YOY_DIFF_BKD_3, YOY_D0_KZL_3, YOY_KZL_3, DEP_LONGITUDE, DEP_LATITUDE, ARR_LONGITUDE, ARR_LATITUDE, FLY_SEASON, CANCEL_BKG, AFFIRM_BKG, CAPACITY_P, CAPACITY, OD_MARKET_PER, CAP_P, CAP_SUM, COM_MARKET_PER, CAP_C, CAP_COUNT, AREA_MARKET_PER, KZL_P, KZL_HIS_1, KZL_HIS_2, KZL_HIS_3, KZL_HIS_4, KZL_HIS_5, KZL_HIS_6, KZL_HIS_7, FPRICE, CPRICE, ID)
SELECT t.*, %5$s.Nextval
FROM (
    WITH t_0 AS (
        SELECT t.*, FIND_APPR_TIME(istDates, t.CREATE_TIME) AS nearTime
        FROM %2$s t
        LEFT JOIN (
            SELECT FLIGHT_DATE, dep, arr, fltno, CAST(COLLECT(COLLECT_DATE(insert_date)) AS COLLECT_DATES) AS istDates
            FROM %3$s aamh
            GROUP BY FLIGHT_DATE, dep, arr, fltno
        ) t1
        ON t.FLIGHT_DATE = t1.FLIGHT_DATE AND t.DEP = t1.DEP AND t.ARR = t1.ARR AND t.FLIGHT_NO = t1.fltno
    ),
    t_1 AS (
        SELECT t.*, (CASE WHEN t1.DAYS IS NULL THEN 0 ELSE t1.DAYS END) AS HOLIDAY
        FROM t_0 t
        LEFT JOIN %4$s t1
        ON t.FLIGHT_DATE = t1.HOLIDAY
    )
    SELECT t.FLIGHT_DATE, AIR_CODE, FLIGHT_NO, DEP_TIME, t.DEP, t.ARR, CREATE_TIME, LABEL, TOP_1, TOP_2, TOP_3, TOP_4,
        TOP_5, TOP_6, FEA_AIR_CODE, FEA_FLIGHT_NO, FEA_DEP, FEA_ARR, t.EX_DIF, FEA_HR, FEA_HR_CLASS, AIRCODE_CLASS,
        FEA_NEAREST_TIME_1, FEA_NEAREST_TIME_2, FEA_DELT_DEPTIME, TOP_MEAN, TOP_MAX, TOP_MIN, TOP_STD,
        (CASE WHEN t.STD_PRICE > 0 THEN t.STD_PRICE WHEN t.STD_PRICE = 0 and t1.STD_PRICE > 0 THEN t1.STD_PRICE END) as STD_PRICE,
        FLIGHTS_SELF, FLIGHTS_TOTAL, POWER, FEA_MONTH, FEA_DAY, FEA_WEEK, FLIGHT_TYPE_CODE, SINGLE_LEG_TIME,
        AC_SINGLE_LEG_TIME, LAST_3_FLY_NUM, LAST_3_FLY_COUNT, LAST_3_FLY_RATE, LAST_2_FLY_NUM, LAST_2_FLY_COUNT,
        LAST_2_FLY_RATE, LAST_1_FLY_NUM, LAST_1_FLY_COUNT, LAST_1_FLY_RATE, FLY_NUM, FLY_COUNT, FLY_RATE, AFTER_1_FLY_NUM,
        AFTER_1_FLY_COUNT, AFTER_1_FLY_RATE, AFTER_2_FLY_NUM, AFTER_2_FLY_COUNT, AFTER_2_FLY_RATE, AFTER_3_FLY_NUM,
        AFTER_3_FLY_COUNT, AFTER_3_FLY_RATE, LOWEST_FLIGHT_NO, LOWEST_DEP_TIME, LOWEST_PRICE, t.DISTANCE, FD_PRICE,
        DEP_CITY, ARR_CITY, SKEY, t1.FLIGHT_DATE AS H_FLIGHT_DATE, INSERT_DATE, COMP, EQT, FLTNO, DEPTIME, ARRTIME,
        t1.DEP AS H_DEP, t1.ARR AS H_ARR, CAP, "MAX", t1.EX_DIF AS H_EX_DIF, IST_HOUR, OD, BKD, LKZK, REST, KZL, DEPWEEK,
        TIME_PD, TRANSIT, HAO, "HOUR", DEP_MINUTE, t.ARR_TIME, ARR_MINUTE, FLYHOURS, HX, "YEAR", "MONTH", WEEK, SUM_INCOME,
        SUM_INCOME_NEW, HDLX, ZGLSR, t.HOLIDAY, AIR, EQT_CODE, FLIGHTNO, UP_CITY_CODE, DIS_CITY_CODE, HX_CODE, OD_CODE,
        FLY_TIME, Y_CABIN_P, NUMOFSOLD, PRICEARR, FINAL_DEMAND, D0_KZL, "DEMAND", '[]' AS D0_PRICEARR, DIFF_IST_HOUR,
        DETAIL_DIFF_BKD, BKD_SUM, HIS_1, HIS_2, HIS_3, HIS_4, HIS_5, HIS_6, HIS_7, YOY_DATE, YOY_BKD, YOY_REST,
        YOY_BKD_SUM, YOY_DETAIL_DIFF_BKD, YOY_NUMOFSOLD, YOY_PRICEARR, YOY_FINAL_DEMAND, YOY_DEMAND, YOY_KZL, YOY_D0_KZL,
        YOY_BKD_1, YOY_REST_1, YOY_DIFF_BKD_1, YOY_D0_KZL_1, YOY_KZL_1, YOY_BKD_2, YOY_REST_2, YOY_DIFF_BKD_2, YOY_D0_KZL_2,
        YOY_KZL_2, YOY_BKD_3, YOY_REST_3, YOY_DIFF_BKD_3, YOY_D0_KZL_3, YOY_KZL_3, DEP_LONGITUDE, DEP_LATITUDE,
        ARR_LONGITUDE, ARR_LATITUDE, FLY_SEASON, CANCEL_BKG, AFFIRM_BKG, CAPACITY_P, CAPACITY, OD_MARKET_PER, CAP_P,
        CAP_SUM, COM_MARKET_PER, CAP_C, CAP_COUNT, AREA_MARKET_PER, KZL_P, KZL_HIS_1, KZL_HIS_2, KZL_HIS_3, KZL_HIS_4,
        KZL_HIS_5, KZL_HIS_6, KZL_HIS_7, FPRICE, CPRICE
    FROM t_1 t
    LEFT JOIN %3$s t1
    ON t.FLIGHT_DATE = t1.FLIGHT_DATE AND t.DEP = t1.DEP AND t.ARR = t1.ARR AND t.FLIGHT_NO = t1.fltno
    AND t.NEARTIME = t1.INSERT_DATE
) t